CREATE TABLE sync_inbox (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    device_id VARCHAR(120) NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'direktor_appv2',
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    client_mutation_id VARCHAR(150) NOT NULL,
    payload_json JSON NOT NULL,
    status ENUM('pending', 'processing', 'processed', 'failed', 'conflict') NOT NULL DEFAULT 'pending',
    retry_count INT NOT NULL DEFAULT 0,
    received_at DATETIME NOT NULL,
    processing_at DATETIME NULL,
    processed_at DATETIME NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sync_inbox_client_mutation (client_mutation_id),
    KEY idx_sync_inbox_status_received (status, received_at),
    KEY idx_sync_inbox_entity (entity_type, entity_id),
    KEY idx_sync_inbox_user (user_id),
    KEY idx_sync_inbox_company (company_id)
);
