name: direktor_appv2
description: "Direktor mobile app base scaffold."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.0
  file_picker: ^8.1.2
  geolocator: ^13.0.4
  intl: ^0.20.2
  path: ^1.9.1
  pdf: ^3.11.1
  printing: ^5.13.4
  qr_flutter: ^4.1.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/direktor_mobile_v2.sql
    - assets/Iimages/isotipoD.png
